version: '3'

services:
  # Database
  db:
    image: lscr.io/linuxserver/mariadb
    #platform: linux/x86_64
    # volume adress ex: /home/newgen/wordpress1/database !!!!
    volumes:
      - /home/newgen/wordpress1/database:/config
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    networks:
      - wpnw
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: arm64v8/phpmyadmin
    restart: always
    ports:
      - '3098:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - wpnw
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8098:80'
    restart: always
    volumes: 
    # volume adress ex: /home/newgen/wordpress1/files !!!
      - /home/newgen/wordpress1/files:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
    networks:
      - wpnw
networks:
  wpnw:
volumes:
  database:
  files:
